FROM python:3.11-slim

WORKDIR /app

COPY backend ./backend
COPY .env ./.env

RUN pip install --no-cache-dir -r ./backend/requirements.txt

ENV PYTHONPATH=/app

EXPOSE 8000

USER nobody
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]